### ISSUE TITLE
Mailing doesn't stop when the replication is fixed

### ISSUE THREAD

**Issue by marianbogdan** [layershift/mysql_replication_monitor#2]
It keeps sending mails even if the nodes are restarted.
Edit: Broke the replication by blocking one node in the other's firewall.
Repaired the replication by removing the block, the env doesn't stop from sending mails.

**Comment by rauladorean** [comment]
fixed in commit  [3dd22a9](https://github.com/layershift/mysql_replication_monitor/commit/3dd22a9aaa4c45f05b194a16479488bf3ed7b6b9)
